---
- name: Ensure MariaDB is installed and running
  hosts: database_dev
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
  tasks:

    - name: Install MariaDB
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ mariadb_packages }}"

    - name: Start MariaDB service
      service:
        name: mariadb
        state: started
        enabled: true

