---
- name: Schedule tasks
  hosts: webservers
  tasks:

    - name: Create cron job
      cron:
        name: Disk Usage
        weekday: "1-5"
        minute: "*/2"
        hour: "9-16"
        user: devops
        job: "df -h >> /home/devops/disk_usage"
        cron_file: disk_usage
        state: present

