---
- name: Configure repo and install packages
  hosts: webservers
  vars:
    pacote: example-motd
  tasks:

    - name: Install gpgkey
      rpm_key:
        state: present
        key: http://materials.example.com/yum/repository/RPM-GPG-KEY-example

    - name: Config Repo
      yum_repository:
        name: example-repo
        description: YUM repo example
        file: example-repo
        baseurl: http://materials.example.com/yum/repository
        gpgcheck: yes

    - name: Install package
      yum:
        name: "{{ pacote }}"
        state: present
