---
- name: Controle de erros
  hosts: databases
  become: true
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:

    - name: Execute date
      command: date
      register: command_result
      changed_when: false

    - name:
      debug:
        var: command_result.stdout

    - name: Install server

      block:
        - name: Install web package (nome errado)
          yum:
            name: "{{ web_package }}"
            state: latest
          failed_when: web_package == "httpd"

      rescue:
        - name: Install database
          yum:
            name: "{{ db_package }}"
            state: latest

      always:
        - name: Start database
          service:
            name: "{{ db_service }}"
            state: started
