---
- name: Controle de erros
  hosts: databases
  become: true
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Install server

      block:
        - name: Install web package (nome errado)
          yum:
            name: "{{ web_package }}"
            state: latest
          ignore_errors: yes
    
      rescue:
        - name: Install database
          yum:
            name: "{{ db_package }}"
            state: latest

      always:
        - name: Start database
          service:
            name: "{{ db_service }}"
            state: started
